FROM node:22-slim AS base
RUN corepack enable

FROM base AS dependencies
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
COPY apps/server/package.json apps/server/
COPY packages/shared/package.json packages/shared/
RUN --mount=type=secret,id=npm_token pnpm install --frozen-lockfile

FROM dependencies AS build
COPY . .
RUN pnpm build
RUN pnpm deploy --filter=@cosmic-blasters/server --prod /prod/server

FROM base AS production
COPY --from=build /prod/server /app
WORKDIR /app
EXPOSE 8080
CMD ["node", "dist/index.js"]
